src/main/webapp/WEB-INF/views/manager/mUser/mUserList.jsp
src/main/webapp/WEB-INF/views/manager/mUser/mUserLog.jsp

10_26 관리자 유저 리스트

---

src/main/webapp/WEB-INF/views/manager/mUser/mUserList.jsp

10_26 유저리스트 수정바람

---

src/main/webapp/WEB-INF/views/manager/common/mLeftBar.jsp
src/main/webapp/WEB-INF/views/manager/mNotice/mNoticeMail.jsp

10_27_09_31

---

src/main/webapp/WEB-INF/views/user/product/productDetail.jsp

당분간은 vs코드에서 반복적으로 별 찍는거 작업 하겠습니다.

---

src/main/webapp/resources/css/mNoticeMail.css
src/main/webapp/resources/css/mPayBuyDetail.css
src/main/webapp/resources/css/mPayBuyList.css
src/main/webapp/resources/css/mPayExchange.css
src/main/webapp/resources/css/mPayRefundDetail.css
src/main/webapp/resources/css/mPayRefundList.css
src/main/webapp/resources/css/mUserList.css
src/main/webapp/resources/css/mUserLog.css

10_28 css 포함

---

src/main/webapp/resources/css/mPayRefundDetail.css

20-10-28 환불디테일 css수정

---

src/main/java/com/fp/neezit/user/controller/UserContoller.java
src/main/webapp/WEB-INF/views/user/signUp.jsp
src/main/webapp/resources/css/loading.css

10_30 회원가입 jsp 퀄리티 업

---

src/main/webapp/WEB-INF/views/user/signUp.jsp

10_30 가입퀄리티 최신판

---

src/main/webapp/WEB-INF/views/user/signUp.jsp

10_30_회원가입 퀄리티업

---

pom.xml
src/main/java/com/fp/neezit/product/controller/ProductController.java
src/main/java/com/fp/neezit/product/model/dao/ProductDao.java
src/main/java/com/fp/neezit/product/model/dao/ProductDaoImpl.java
src/main/java/com/fp/neezit/product/model/service/ProductService.java
src/main/java/com/fp/neezit/product/model/service/ProductServiceImpl.java
src/main/java/com/fp/neezit/product/model/vo/ProductCategory.java
src/main/resources/mappers/product-mapper.xml
src/main/resources/mybatis-config.xml
src/main/webapp/WEB-INF/views/common/nav.jsp
src/main/webapp/WEB-INF/views/user/product/productInsert.jsp
src/main/webapp/WEB-INF/views/user/product/productList.jsp
src/main/webapp/resources/css/productInsert.css

네브바 리스트, 상품등록 셀렉트 박스 성공

---

src/main/java/com/fp/neezit/user/controller/UserContoller.java
src/main/java/com/fp/neezit/user/model/dao/UserDao.java
src/main/java/com/fp/neezit/user/model/service/UserService.java
src/main/java/com/fp/neezit/user/model/service/UserServiceImpl.java
src/main/webapp/WEB-INF/views/user/signUpMaster.jsp

능력자등록 카테고리

---

src/main/webapp/WEB-INF/views/user/signUp.jsp
src/main/webapp/resources/css/signUp.css

11_01 제한시간

---

src/main/java/com/fp/neezit/user/controller/UserContoller.java
src/main/java/com/fp/neezit/user/model/dao/UserDao.java
src/main/java/com/fp/neezit/user/model/service/UserService.java
src/main/java/com/fp/neezit/user/model/service/UserServiceImpl.java
src/main/resources/mappers/user-mapper.xml
src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/user/login.jsp
src/main/webapp/WEB-INF/views/user/myPage/common/nav.jsp
src/main/webapp/WEB-INF/views/user/myPage/deleteUser.jsp
src/main/webapp/WEB-INF/views/user/myPage/modifyPwd.jsp

hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정hedaerCSS수정

천동민천동민천동민천동민천동민천동민

---

src/main/webapp/WEB-INF/views/common/header.jsp

qwdqwdqwdqwdqwd

---

src/main/java/com/fp/neezit/product/controller/ProductController.java
src/main/java/com/fp/neezit/product/model/dao/ProductDao.java
src/main/java/com/fp/neezit/product/model/service/ProductService.java
src/main/java/com/fp/neezit/product/model/service/ProductServiceImpl.java
src/main/java/com/fp/neezit/product/model/vo/Product.java
src/main/resources/mappers/product-mapper.xml
src/main/resources/mybatis-config.xml
src/main/webapp/WEB-INF/views/user/product/productInsert.jsp
src/main/webapp/resources/css/productInsert.css

11_04 잉기모링

---

src/main/webapp/resources/css/productInsert.css

11_07 헤더 재 확인

---

src/main/java/com/fp/neezit/IndexController.java
src/main/java/com/fp/neezit/user/controller/UserContoller.java
src/main/webapp/WEB-INF/views/common/header.jsp

Controller의 Session은 각자 초기화시켜야주어야함.

header 수정,

---

src/main/webapp/WEB-INF/views/common/header.jsp

비로그인시 header에 관리자 표시

---

src/main/webapp/WEB-INF/views/user/signUpMaster.jsp
src/main/webapp/resources/css/signUpMaster.css

능력자 등록 조금 수정

---

src/main/java/com/fp/neezit/user/controller/UserContoller.java
src/main/java/com/fp/neezit/user/model/vo/Pagination.java
src/main/webapp/WEB-INF/views/user/myPage/walletDetail.jsp

11_14 유저컨트롤러, 월렛디테일, 카카오페이, 출금쪽 없어진거 복구 및 작업했던 기능들 기능 확인

11_14 유저컨트롤러, 월렛디테일, 카카오페이, 출금쪽 없어진거 복구 및 작업했던 기능들 기능 확인

---

src/main/java/com/fp/neezit/product/controller/ProductController.java

ProdcutController 468~ 498 만들었습니다.

fjgjfgfgjjfgjgf

---

src/main/webapp/WEB-INF/views/user/product/productDetail.jsp

프로덕트 디테일 상뉴가 말한 2가지

---

src/main/java/com/fp/neezit/product/controller/ProductController.java
src/main/java/com/fp/neezit/product/model/vo/Product.java
src/main/resources/mappers/product-mapper.xml
src/main/webapp/WEB-INF/views/user/product/productList.jsp
src/main/webapp/resources/css/loading2.css

1. 무한스크롤 적용 완료
2. addedStar(); 별점 뿌려주기 완료
3. filter(); 적용 완료

1. 무한스크롤 적용 완료

---

src/main/java/com/fp/neezit/user/controller/UserMyPageController.java
src/main/resources/mappers/product-mapper.xml

11_16 문제되는 작업 수정

---

src/main/java/com/fp/neezit/product/controller/ProductController.java

11_16 컨트롤러 겹치는 문제 해결

---

src/main/java/com/fp/neezit/product/controller/ProductController.java
src/main/java/com/fp/neezit/product/model/dao/ProductDao.java
src/main/java/com/fp/neezit/product/model/service/ProductService.java
src/main/java/com/fp/neezit/product/model/service/ProductServiceImpl.java
src/main/resources/mappers/product-mapper.xml
src/main/webapp/WEB-INF/views/user/product/myProductDetail.jsp
src/main/webapp/WEB-INF/views/user/product/myProductList.jsp
src/main/webapp/WEB-INF/views/user/product/productUpdate.jsp
src/main/webapp/resources/css/myProductList.css
src/main/webapp/resources/css/productInsert.css

11-16 상품수정 및 삭제 완료

---

src/main/java/com/fp/neezit/product/controller/ProductController.java

11-16 상품수정 완료

---

src/main/java/com/fp/neezit/manager/controller/ManagerController.java
src/main/java/com/fp/neezit/manager/model/dao/ManagerDao.java
src/main/java/com/fp/neezit/manager/model/service/ManagerService.java
src/main/java/com/fp/neezit/manager/model/service/ManagerServiceImpl.java
src/main/java/com/fp/neezit/manager/model/vo/PageInfo.java
src/main/java/com/fp/neezit/manager/model/vo/Pagination.java
src/main/java/com/fp/neezit/manager/model/vo/UserBean.java
src/main/java/com/fp/neezit/manager/model/vo/UserList.java
src/main/java/com/fp/neezit/user/model/vo/User.java
src/main/java/com/fp/neezit/user/model/vo/UserMaster.java
src/main/resources/mappers/manager-mapper.xml
src/main/resources/mybatis-config.xml
src/main/webapp/WEB-INF/views/manager/mUser/mUserList.jsp
src/main/webapp/resources/css/mUserList.css

관리자 회원리스트 절반 완성

---

src/main/java/com/fp/neezit/user/controller/UserMyPageController.java
src/main/java/com/fp/neezit/user/model/dao/UserDao.java
src/main/java/com/fp/neezit/user/model/service/UserService.java
src/main/java/com/fp/neezit/user/model/service/UserServiceImpl.java
src/main/java/com/fp/neezit/user/model/vo/UserBuyList.java
src/main/resources/mappers/user-mapper.xml
src/main/webapp/WEB-INF/views/user/product/productDetail.jsp

20_11_18
[productDetail.jsp]
677~703 상품평 작성 버튼 눌렀을 때 DB 구매내역에 이력이 있는지 확인하는 AJAX
[UserMyPageController]
445~470 buyConfirm.do 컨트롤러 구현
....
[user-mapper.xml]
483~ 이메일과 상품번호를 통해 구매내역에 로그인한 회원의 정보가 있는지 count.
1 이상이면 구매한 이력이 있는 것
[UserBuyList.java]
vo에 상품번호 객체 추가
DB BUYLIST 테이블에 USER_PNO 추가

Mhr / reply buy confirm

---

src/main/java/com/fp/neezit/manager/controller/ManagerController.java
src/main/java/com/fp/neezit/manager/model/dao/ManagerDao.java
src/main/java/com/fp/neezit/manager/model/service/ManagerService.java
src/main/java/com/fp/neezit/manager/model/service/ManagerServiceImpl.java
src/main/java/com/fp/neezit/manager/model/vo/UserBean.java
src/main/java/com/fp/neezit/manager/model/vo/UserList.java
src/main/java/com/fp/neezit/product/controller/ProductController.java
src/main/java/com/fp/neezit/user/controller/UserContoller.java
src/main/java/com/fp/neezit/user/controller/UserMasterController.java
src/main/resources/mappers/manager-mapper.xml
src/main/webapp/WEB-INF/views/manager/mBoard/mBoardForbidden.jsp
src/main/webapp/WEB-INF/views/manager/mUser/mUserList.jsp
src/main/webapp/WEB-INF/views/user/product/productDetail.jsp
src/main/webapp/WEB-INF/views/user/product/productInsert.jsp
src/main/webapp/WEB-INF/views/user/product/productUpdate.jsp
src/main/webapp/WEB-INF/views/user/signUpMaster.jsp
src/main/webapp/WEB-INF/views/user/siguUPMasterUpdate.jsp
src/main/webapp/resources/css/mBoardForbidden.css

관리자 회원리스트 거의 완성, 금칙어 일부 수정 // 사용자 금칙어 필터 적용 완료

관리자 회원리스트 거의 완성, 금칙어 일부 수정 // 사용자 금칙어 필터 적용 완료

---

src/main/java/com/fp/neezit/IndexController.java
src/main/java/com/fp/neezit/user/controller/UserContoller.java
src/main/java/com/fp/neezit/user/model/dao/UserDao.java
src/main/java/com/fp/neezit/user/model/service/UserService.java
src/main/java/com/fp/neezit/user/model/service/UserServiceImpl.java
src/main/java/com/fp/neezit/user/model/vo/Admin.java
src/main/resources/mappers/user-mapper.xml
src/main/resources/mybatis-config.xml
src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/resources/css/header.css

헤더 작업 + 관리자 접속 추가

---

src/main/java/com/fp/neezit/user/controller/UserContoller.java
src/main/java/com/fp/neezit/user/model/dao/UserDao.java
src/main/java/com/fp/neezit/user/model/service/KakaoService.java
src/main/java/com/fp/neezit/user/model/service/UserService.java
src/main/java/com/fp/neezit/user/model/service/UserServiceImpl.java
src/main/resources/mappers/user-mapper.xml
src/main/webapp/WEB-INF/views/common/footer.jsp
src/main/webapp/WEB-INF/views/common/header.jsp
src/main/webapp/WEB-INF/views/user/login.jsp
src/main/webapp/resources/css/header.css
src/main/webapp/resources/css/login.css

Cdm kakao login

---

src/main/java/com/fp/neezit/manager/controller/ManagerController.java
src/main/java/com/fp/neezit/manager/model/dao/ManagerDao.java
src/main/java/com/fp/neezit/manager/model/service/ManagerService.java
src/main/java/com/fp/neezit/manager/model/service/ManagerServiceImpl.java
src/main/java/com/fp/neezit/product/controller/ProductController.java
src/main/resources/mappers/manager-mapper.xml
src/main/webapp/WEB-INF/views/manager/mUser/mMasterConfirm.jsp
src/main/webapp/resources/css/mMasterConfirm.css

관리자 회원리스트 인증방법 수정
